home_kubeconfig: /home/chris/.kube/klaital/kubeconfig

branch_deployment_configs:
  master: 
    namespace: master
    kubeconfig:
    k8s_deployment:
    host: ''
    username: ''
    sshkey: 
  deploy-stage: 
    namespace: vita-stage
    kubeconfig: /home/chris/.kube/klaital/kubeconfig
    k8s_deployment: run/stage.yaml
    host: ''
    username: ''
    sshkey: 
  deploy-prod: 
    namespace: vita-prod
    kubeconfig: 
    k8s_deployment: 
    host: 159.89.130.190
    username: vita
    sshkey: /home/chris/.ssh/vita_id_rsa
  

